name: Deploy Ma Section

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer les fichiers
        uses: actions/checkout@v4

      - name: Configurer GitHub Pages
        uses: actions/configure-pages@v5

      - name: Préparer le site
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Publier le site
        uses: actions/deploy-pages@v4
